# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3561af4fb911ca23c4823875d7964d5f9db703700b5d02317e3191c3f0b03e6ed2ae66c4c0d7d50a2551923c3cd32757caf034286564896fa5d509e1d1d025f9

test:
  secret_key_base: 3c407d207075400c676379367642abe8f45be25f4347bcbe22f1852bffd5b5b57a7ba6e752abefe15b0fdea278d625a671cf50c0ad68a0b12c7c42b5aca81eaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
